apiVersion: v1
kind: PersistentVolume
metadata:
  name: project2-pv2-lorraynesantos
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default-storage-class-lorraynesantos
  hostPath:
    path: /mnt/project2-pv2-lorraynesantos
