apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: lisker/flask-docker:latest
        env:
        - name: version
          value: "1.0"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: project2-pv2-lorraynesantos
          mountPath: /app/data
      restartPolicy: Always
      volumes:
      - name: project2-pv2-lorraynesantos
        persistentVolumeClaim:
          claimName: project2-pv2-lorraynesantos
