apiVersion: batch/v1
kind: Job
metadata:
  name: rules
  namespace: lorraynesantos
spec:
  template:
    metadata:
      labels:
        app: rules
    spec:
      containers:
      - name: rules
        image: lorraynesantos/rules:2.0.0
        env:
        - name: CSV_FILENAME
          value: "https://raw.githubusercontent.com/somerlatte/cloud-computing_project2/refs/heads/main/data/2023_spotify_ds2.csv"
        volumeMounts:
        - name: shared-volume
          mountPath: /mnt/shared
      restartPolicy: Never
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: project2-pv2-lorraynesantos
  backoffLimit: 1
