apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-lorraynesantos-claim
  namespace: lorraynesantos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: lorraynesantos
  storageClassName: default-storage-class-lorraynesantos
